import { useState } from "react"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { useAuth } from "@/hooks/use-auth"
import { useToast } from "@/hooks/use-toast"
import { getToken } from "@/lib/auth"
import { cn } from "@/lib/utils"
import {
  Percent,
  Lock,
  Pencil,
  Loader2,
  Info,
  ShieldAlert,
  CheckCircle2,
  XCircle,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  Alert,
  AlertDescription,
} from "@/components/ui/alert"

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface VatSetting {
  id: number
  firmId: number
  code: string
  label: string
  ratePercentage: number
  salesAccount: string | null
  purchaseAccount: string | null
  isActive: boolean
  isEditable: boolean
  updatedById: number | null
  updatedByName: string | null
  createdAt: string
  updatedAt: string
}

// ---------------------------------------------------------------------------
// API helpers (inline — not generated by Orval)
// ---------------------------------------------------------------------------

const API_BASE = "/api"

async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const token = getToken()
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(options?.headers ?? {}),
    },
  })
  if (!res.ok) {
    const body = await res.json().catch(() => ({}))
    throw new Error(
      (body as { error?: string }).error ??
        `Erreur serveur (${res.status})`,
    )
  }
  return res.json() as Promise<T>
}

// ---------------------------------------------------------------------------
// CODE badge color map
// ---------------------------------------------------------------------------

const CODE_COLORS: Record<string, string> = {
  TVA_18: "bg-blue-100 text-blue-800 border-blue-200",
  TVA_9:  "bg-violet-100 text-violet-800 border-violet-200",
  TVA_EXO: "bg-emerald-100 text-emerald-800 border-emerald-200",
}

// Tooltip explanations for each code
const CODE_TOOLTIPS: Record<string, string> = {
  TVA_18:
    "Taux standard de TVA applicable à la plupart des biens et services assujettis en Côte d'Ivoire (art. 339 CGI). Compte 443100 au crédit lors de la facturation.",
  TVA_9:
    "Taux réduit de TVA applicable aux produits et services désignés par décret (art. 340 CGI). Compte 443200 au crédit lors de la facturation.",
  TVA_EXO:
    "Opérations exonérées de TVA par la loi (exportations, certains services médicaux, éducatifs…). Aucun compte TVA n'est imputé. Ce paramètre ne peut pas être modifié.",
}

// ---------------------------------------------------------------------------
// Edit dialog
// ---------------------------------------------------------------------------

interface EditDialogProps {
  setting: VatSetting | null
  open: boolean
  onClose: () => void
  onSaved: (updated: VatSetting) => void
}

function EditDialog({ setting, open, onClose, onSaved }: EditDialogProps) {
  const [rate, setRate] = useState("")
  const [salesAcc, setSalesAcc] = useState("")
  const [purchaseAcc, setPurchaseAcc] = useState("")
  const [active, setActive] = useState(true)
  const { toast } = useToast()

  // Populate form when dialog opens with a setting
  const handleOpenChange = (isOpen: boolean) => {
    if (isOpen && setting) {
      setRate(setting.ratePercentage.toString())
      setSalesAcc(setting.salesAccount ?? "")
      setPurchaseAcc(setting.purchaseAccount ?? "")
      setActive(setting.isActive)
    }
    if (!isOpen) onClose()
  }

  const mutation = useMutation({
    mutationFn: async () => {
      if (!setting) throw new Error("Aucun paramètre sélectionné.")

      const rateNum = parseFloat(rate)
      if (isNaN(rateNum) || rateNum < 0 || rateNum > 100) {
        throw new Error("Le taux doit être compris entre 0 et 100 %.")
      }
      if (salesAcc && !/^\d{4,8}$/.test(salesAcc)) {
        throw new Error("Le compte TVA collectée doit être un code SYSCOHADA de 4 à 8 chiffres.")
      }
      if (purchaseAcc && !/^\d{4,8}$/.test(purchaseAcc)) {
        throw new Error("Le compte TVA déductible doit être un code SYSCOHADA de 4 à 8 chiffres.")
      }

      return apiFetch<VatSetting>(`/cabinet/vat-settings/${setting.id}`, {
        method: "PUT",
        body: JSON.stringify({
          ratePercentage: rateNum,
          salesAccount: salesAcc || null,
          purchaseAccount: purchaseAcc || null,
          isActive: active,
        }),
      })
    },
    onSuccess: (updated) => {
      toast({
        title: "Paramètre TVA mis à jour",
        description: `Le code ${updated.code} a été enregistré avec succès.`,
      })
      onSaved(updated)
      onClose()
    },
    onError: (err: Error) => {
      toast({
        title: "Erreur de mise à jour",
        description: err.message,
        variant: "destructive",
      })
    },
  })

  if (!setting) return null

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Pencil className="h-4 w-4 text-primary" />
            Modifier — {setting.label}
          </DialogTitle>
          <DialogDescription>
            Ajustez le taux ou les comptes SYSCOHADA associés à ce code TVA. Toute
            modification prend effet immédiatement sur les nouvelles factures et
            écritures comptables.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-5 py-2">
          {/* Rate */}
          <div className="space-y-2">
            <Label htmlFor="vat-rate" className="text-sm font-medium">
              Taux TVA (%)
            </Label>
            <div className="relative">
              <Input
                id="vat-rate"
                type="number"
                min="0"
                max="100"
                step="0.01"
                value={rate}
                onChange={(e) => setRate(e.target.value)}
                className="pr-8"
                placeholder="18"
              />
              <span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-sm text-muted-foreground">
                %
              </span>
            </div>
            <p className="text-xs text-muted-foreground">
              Valeur actuelle : <strong>{setting.ratePercentage} %</strong>
            </p>
          </div>

          {/* Sales account */}
          <div className="space-y-2">
            <Label htmlFor="sales-account" className="text-sm font-medium">
              Compte TVA collectée (ventes)
            </Label>
            <Input
              id="sales-account"
              value={salesAcc}
              onChange={(e) => setSalesAcc(e.target.value)}
              placeholder={setting.salesAccount ?? "ex. 443100"}
              maxLength={8}
            />
            <p className="text-xs text-muted-foreground">
              Compte SYSCOHADA crédité lors de la validation d'une facture de vente. Exemple : <code className="rounded bg-muted px-1">443100</code>
            </p>
          </div>

          {/* Purchase account */}
          <div className="space-y-2">
            <Label htmlFor="purchase-account" className="text-sm font-medium">
              Compte TVA déductible (achats)
            </Label>
            <Input
              id="purchase-account"
              value={purchaseAcc}
              onChange={(e) => setPurchaseAcc(e.target.value)}
              placeholder={setting.purchaseAccount ?? "ex. 445200"}
              maxLength={8}
            />
            <p className="text-xs text-muted-foreground">
              Compte SYSCOHADA débité pour la TVA récupérable sur biens et services. Exemple : <code className="rounded bg-muted px-1">445200</code>
            </p>
          </div>

          {/* Active toggle */}
          <div className="flex items-center justify-between rounded-lg border p-3.5">
            <div className="space-y-0.5">
              <Label className="text-sm font-medium">Code actif</Label>
              <p className="text-xs text-muted-foreground">
                Un code inactif n'apparaît plus dans les menus de saisie.
              </p>
            </div>
            <Switch checked={active} onCheckedChange={setActive} />
          </div>

          {/* Warning */}
          <Alert className="border-amber-200 bg-amber-50">
            <ShieldAlert className="h-4 w-4 text-amber-600" />
            <AlertDescription className="text-xs text-amber-800">
              Cette modification affecte toutes les nouvelles factures et déclarations TVA
              générées par votre cabinet. Les écritures déjà comptabilisées ne sont
              pas rétroactivement modifiées.
            </AlertDescription>
          </Alert>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={mutation.isPending}>
            Annuler
          </Button>
          <Button onClick={() => mutation.mutate()} disabled={mutation.isPending}>
            {mutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
            Enregistrer
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

export default function VatSettings() {
  const { user } = useAuth()
  const queryClient = useQueryClient()
  const [editTarget, setEditTarget] = useState<VatSetting | null>(null)
  const [editOpen, setEditOpen] = useState(false)

  const canEdit =
    user?.role === "expert_comptable" || user?.role === "collaborateur"
  const isPortal =
    user?.role !== "expert_comptable" &&
    user?.role !== "collaborateur" &&
    user?.role !== "stagiaire"

  const { data: settings = [], isLoading } = useQuery<VatSetting[]>({
    queryKey: ["vat-settings", user?.firmId],
    queryFn: () => apiFetch<VatSetting[]>("/cabinet/vat-settings"),
    enabled: !!user,
  })

  const handleEdit = (setting: VatSetting) => {
    setEditTarget(setting)
    setEditOpen(true)
  }

  const handleSaved = (updated: VatSetting) => {
    queryClient.setQueryData<VatSetting[]>(
      ["vat-settings", user?.firmId],
      (prev) => prev?.map((s) => (s.id === updated.id ? updated : s)) ?? [updated],
    )
  }

  if (isPortal) {
    return (
      <div className="mx-auto max-w-3xl space-y-6 p-6">
        <Alert className="border-amber-200 bg-amber-50">
          <ShieldAlert className="h-4 w-4 text-amber-600" />
          <AlertDescription className="text-amber-800">
            La configuration des paramètres TVA est réservée aux collaborateurs du cabinet.
            Veuillez contacter votre comptable pour toute modification.
          </AlertDescription>
        </Alert>
      </div>
    )
  }

  return (
    <TooltipProvider>
      <div className="mx-auto max-w-4xl space-y-6 p-6">
        {/* Page header */}
        <div className="flex items-start gap-3">
          <div className="rounded-lg border bg-muted/40 p-2">
            <Percent className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="text-xl font-semibold tracking-tight">
              Configuration des Taxes (TVA)
            </h1>
            <p className="text-sm text-muted-foreground">
              Taux et comptes SYSCOHADA appliqués lors des saisies de factures et déclarations TVA — Module M21
            </p>
          </div>
        </div>

        {/* Read-only notice for stagiaire */}
        {user?.role === "stagiaire" && (
          <Alert className="border-blue-200 bg-blue-50">
            <Info className="h-4 w-4 text-blue-600" />
            <AlertDescription className="text-blue-800 text-sm">
              Vous consultez les paramètres TVA en lecture seule. Seuls les{" "}
              <strong>Experts-Comptables</strong> et <strong>Collaborateurs</strong> peuvent
              modifier ces valeurs.
            </AlertDescription>
          </Alert>
        )}

        {/* Main settings card */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div>
                <CardTitle className="text-base">Codes TVA configurables</CardTitle>
                <CardDescription className="mt-0.5 text-xs">
                  Chaque code définit un taux applicable et les comptes SYSCOHADA utilisés à la
                  comptabilisation.
                </CardDescription>
              </div>
            </div>
          </CardHeader>

          <CardContent className="p-0">
            {isLoading ? (
              <div className="flex items-center justify-center py-12">
                <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
              </div>
            ) : (
              <div className="divide-y">
                {/* Desktop column headers — hidden on mobile */}
                <div className="hidden md:grid md:grid-cols-[minmax(0,2fr)_80px_140px_140px_80px_110px] gap-3 px-6 py-2.5 text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  <span>Code TVA</span>
                  <span>Taux</span>
                  <span>Compte collectée</span>
                  <span>Compte déductible</span>
                  <span>Statut</span>
                  <span className="text-right">Action</span>
                </div>

                {settings.map((setting) => (
                  <VatSettingRow
                    key={setting.id}
                    setting={setting}
                    canEdit={canEdit}
                    onEdit={handleEdit}
                  />
                ))}

                {settings.length === 0 && !isLoading && (
                  <div className="px-6 py-8 text-center text-sm text-muted-foreground">
                    Aucun paramètre TVA configuré.
                  </div>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Info panel */}
        <Card className="border-muted bg-muted/20">
          <CardContent className="p-5">
            <div className="flex items-start gap-3">
              <Info className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
              <div className="space-y-2 text-xs text-muted-foreground">
                <p>
                  <strong className="text-foreground">Comptes SYSCOHADA :</strong> Ces codes
                  correspondent au Plan Comptable SYSCOHADA Révisé appliqué en Côte d'Ivoire.
                  Les comptes de classe 44 (État et collectivités publiques) ne doivent être
                  modifiés qu'en cas de changement officiel du plan comptable ou d'une
                  instruction de la DGI.
                </p>
                <p>
                  <strong className="text-foreground">Compte 443100</strong> — TVA facturée sur
                  ventes au taux normal (18 %). Crédité à chaque validation de facture de vente.
                </p>
                <p>
                  <strong className="text-foreground">Compte 443200</strong> — TVA facturée sur
                  ventes au taux réduit (9 %). Crédité pour les prestations à taux réduit.
                </p>
                <p>
                  <strong className="text-foreground">Compte 445200</strong> — TVA récupérable
                  sur achats de biens et services courants. Débité lors de la saisie des achats
                  assujettis. (Le compte 445100, dédié aux immobilisations, est géré
                  automatiquement par le module Immobilisations.)
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Edit dialog */}
        <EditDialog
          setting={editTarget}
          open={editOpen}
          onClose={() => setEditOpen(false)}
          onSaved={handleSaved}
        />
      </div>
    </TooltipProvider>
  )
}

// ---------------------------------------------------------------------------
// Row component
// ---------------------------------------------------------------------------

interface VatSettingRowProps {
  setting: VatSetting
  canEdit: boolean
  onEdit: (s: VatSetting) => void
}

function VatSettingRow({ setting, canEdit, onEdit }: VatSettingRowProps) {
  const badgeCls = CODE_COLORS[setting.code] ?? "bg-slate-100 text-slate-700 border-slate-200"
  const tooltip = CODE_TOOLTIPS[setting.code]

  const formattedDate = setting.updatedById
    ? new Intl.DateTimeFormat("fr-FR", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }).format(new Date(setting.updatedAt))
    : null

  const badge = (
    <Tooltip>
      <TooltipTrigger asChild>
        <span
          className={cn(
            "inline-flex shrink-0 items-center gap-1 rounded-md border px-2 py-0.5 text-[11px] font-semibold tracking-wide cursor-default",
            badgeCls,
          )}
        >
          {!setting.isEditable && <Lock className="h-2.5 w-2.5" />}
          {setting.code}
        </span>
      </TooltipTrigger>
      {tooltip && (
        <TooltipContent side="right" className="max-w-xs text-xs">
          {tooltip}
        </TooltipContent>
      )}
    </Tooltip>
  )

  const statusEl = setting.isActive ? (
    <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">
      <CheckCircle2 className="h-3.5 w-3.5" /> Actif
    </span>
  ) : (
    <span className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground">
      <XCircle className="h-3.5 w-3.5" /> Inactif
    </span>
  )

  const actionEl = setting.isEditable && canEdit ? (
    <Button
      size="sm"
      variant="outline"
      className="h-8 gap-1.5 text-xs"
      onClick={() => onEdit(setting)}
    >
      <Pencil className="h-3 w-3" />
      Modifier
    </Button>
  ) : setting.isEditable && !canEdit ? (
    <span className="text-xs text-muted-foreground italic">Lecture seule</span>
  ) : (
    <div className="flex items-center gap-1 text-xs text-muted-foreground">
      <Lock className="h-3 w-3" />
      <span>Fixé par la loi</span>
    </div>
  )

  return (
    <>
      {/* ── Mobile card (< md) ─────────────────────────────────────── */}
      <div
        className={cn(
          "md:hidden px-4 py-4 space-y-3",
          !setting.isActive && "opacity-50",
        )}
      >
        {/* Header row: badge + label + action */}
        <div className="flex items-start justify-between gap-2">
          <div className="flex items-center gap-2 min-w-0">
            {badge}
            <div className="min-w-0">
              <p className="text-sm font-semibold leading-snug">{setting.label}</p>
              {setting.updatedByName && formattedDate && (
                <p className="text-[10px] text-muted-foreground">
                  Modifié par {setting.updatedByName} le {formattedDate}
                </p>
              )}
            </div>
          </div>
          <div className="shrink-0">{actionEl}</div>
        </div>

        {/* Detail grid: 2×2 key-value */}
        <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-sm">
          <div>
            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground mb-0.5">Taux</p>
            <span className="font-semibold tabular-nums">
              {setting.ratePercentage.toLocaleString("fr-FR", { maximumFractionDigits: 2 })} %
            </span>
          </div>
          <div>
            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground mb-0.5">Statut</p>
            {statusEl}
          </div>
          <div>
            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground mb-0.5">Collectée</p>
            <AccountCell
              account={setting.salesAccount}
              tooltip="Compte SYSCOHADA crédité (TVA collectée) lors de la validation d'une facture de vente."
              emptyLabel="Non imputé"
            />
          </div>
          <div>
            <p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground mb-0.5">Déductible</p>
            <AccountCell
              account={setting.purchaseAccount}
              tooltip="Compte SYSCOHADA débité (TVA déductible) lors de la saisie d'un achat assujetti."
              emptyLabel="Non imputé"
            />
          </div>
        </div>
      </div>

      {/* ── Desktop table row (≥ md) ───────────────────────────────── */}
      <div
        className={cn(
          "hidden md:grid md:grid-cols-[minmax(0,2fr)_80px_140px_140px_80px_110px] items-center gap-3 px-6 py-4",
          !setting.isActive && "opacity-50",
        )}
      >
        {/* Code + label */}
        <div className="flex items-center gap-2 min-w-0">
          {badge}
          <div className="min-w-0">
            <p className="truncate text-sm font-medium">{setting.label}</p>
            {setting.updatedByName && formattedDate && (
              <p className="text-[10px] text-muted-foreground">
                Modifié par {setting.updatedByName} le {formattedDate}
              </p>
            )}
          </div>
        </div>

        {/* Rate */}
        <span className="text-sm font-semibold tabular-nums">
          {setting.ratePercentage.toLocaleString("fr-FR", { maximumFractionDigits: 2 })} %
        </span>

        {/* Sales account */}
        <AccountCell
          account={setting.salesAccount}
          tooltip="Compte SYSCOHADA crédité (TVA collectée) lors de la validation d'une facture de vente."
          emptyLabel="Non imputé"
        />

        {/* Purchase account */}
        <AccountCell
          account={setting.purchaseAccount}
          tooltip="Compte SYSCOHADA débité (TVA déductible) lors de la saisie d'un achat assujetti."
          emptyLabel="Non imputé"
        />

        {/* Active status */}
        <div>{statusEl}</div>

        {/* Action */}
        <div className="flex justify-end">{actionEl}</div>
      </div>
    </>
  )
}

// ---------------------------------------------------------------------------
// Account display cell
// ---------------------------------------------------------------------------

function AccountCell({
  account,
  tooltip,
  emptyLabel,
}: {
  account: string | null
  tooltip: string
  emptyLabel: string
}) {
  if (!account) {
    return (
      <span className="text-xs italic text-muted-foreground">{emptyLabel}</span>
    )
  }

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className="inline-flex items-center gap-1.5 cursor-default">
            <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs font-mono font-medium text-slate-700">
              {account}
            </code>
          </span>
        </TooltipTrigger>
        <TooltipContent side="top" className="max-w-xs text-xs">
          {tooltip}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
