import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import auditLogsRouter from "./audit-logs";
import dashboardRouter from "./dashboard";
import clientsRouter from "./clients";
import documentsRouter from "./documents";
import missionsRouter from "./missions";
import accountingRouter from "./accounting";
import caisseRouter from "./caisse";
import cabinetRouter from "./cabinet";
import reportingRouter from "./reporting";
import fixedAssetsRouter from "./fixed-assets";
import financialItemsRouter from "./financial-items";
import closingRouter from "./closing";
import payrollRouter from "./payroll";
import taxRouter from "./tax";
import cabinetAnalyticsRouter from "./cabinet-analytics";
import analyticalRouter from "./analytical";
import dsfRouter from "./dsf";
import reportDocumentsRouter from "./report-documents";
import collaborationRouter from "./collaboration";
import scoringRouter from "./scoring";
import invoicingRouter from "./invoicing";
import staffRouter from "./staff";
import chatRouter from "./chat";
import payrollSettingsRouter from "./payroll-settings";
import vatSettingsRouter from "./vat-settings";
import pumpShiftsRouter from "./pump-shifts";
import pumpsRouter from "./pumps";
import pumpAssignmentsRouter from "./pump-assignments";
import fuelPricesRouter from "./fuel-prices";
import mobileMoneyRouter from "./mobile-money";
import documentFoldersRouter from "./document-folders";
import stationsRouter from "./stations";
import accountsRouter from "./accounts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(auditLogsRouter);
router.use(dashboardRouter);
router.use(clientsRouter);
router.use(documentsRouter);
router.use(missionsRouter);
router.use(accountingRouter);
router.use(caisseRouter);
router.use(cabinetRouter);
router.use(reportingRouter);
router.use(fixedAssetsRouter);
router.use(financialItemsRouter);
router.use(closingRouter);
router.use(payrollRouter);
router.use(taxRouter);
router.use(cabinetAnalyticsRouter);
router.use(analyticalRouter);
router.use(dsfRouter);
router.use(reportDocumentsRouter);
router.use(collaborationRouter);
router.use(scoringRouter);
router.use(invoicingRouter);
router.use(staffRouter);
router.use(chatRouter);
router.use(payrollSettingsRouter);
router.use(vatSettingsRouter);
router.use(stationsRouter);
router.use(pumpShiftsRouter);
router.use(pumpsRouter);
router.use(pumpAssignmentsRouter);
router.use(fuelPricesRouter);
router.use(mobileMoneyRouter);
router.use(documentFoldersRouter);
router.use(accountsRouter);

export default router;
