import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import auditLogsRouter from "./audit-logs";
import dashboardRouter from "./dashboard";
import clientsRouter from "./clients";
import documentsRouter from "./documents";
import missionsRouter from "./missions";
import accountingRouter from "./accounting";
import caisseRouter from "./caisse";
import reportingRouter from "./reporting";
import fixedAssetsRouter from "./fixed-assets";
import financialItemsRouter from "./financial-items";
import closingRouter from "./closing";
import payrollRouter from "./payroll";
import taxRouter from "./tax";
import cabinetAnalyticsRouter from "./cabinet-analytics";
import analyticalRouter from "./analytical";
import dsfRouter from "./dsf";
import reportDocumentsRouter from "./report-documents";
import collaborationRouter from "./collaboration";
import scoringRouter from "./scoring";
import invoicingRouter from "./invoicing";
import staffRouter from "./staff";
import chatRouter from "./chat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(auditLogsRouter);
router.use(dashboardRouter);
router.use(clientsRouter);
router.use(documentsRouter);
router.use(missionsRouter);
router.use(accountingRouter);
router.use(caisseRouter);
router.use(reportingRouter);
router.use(fixedAssetsRouter);
router.use(financialItemsRouter);
router.use(closingRouter);
router.use(payrollRouter);
router.use(taxRouter);
router.use(cabinetAnalyticsRouter);
router.use(analyticalRouter);
router.use(dsfRouter);
router.use(reportDocumentsRouter);
router.use(collaborationRouter);
router.use(scoringRouter);
router.use(invoicingRouter);
router.use(staffRouter);
router.use(chatRouter);

export default router;
