import {
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { firmsTable } from "./firms";
import { clientsTable } from "./clients";
import { usersTable } from "./users";
import { transactionsTable } from "./accounting";
import { invoicesTable } from "./invoicing";

// -- Trésorerie Mobile Money (generalized, all PME clients) -----------------
// Extends the Module P7 station-service Mobile Money foundation
// (MOBILE_MONEY_PROVIDER_ACCOUNTS in accounting-engine.ts) to every PME
// client, not just STATION_SERVICE. A client can hold several merchant
// profiles (one per operator, or several accounts on the same operator).

export const MOBILE_MONEY_PROVIDERS = ["wave", "orange_money", "mtn_momo", "moov_money"] as const;
export type MobileMoneyProvider = (typeof MOBILE_MONEY_PROVIDERS)[number];

export const mobileMoneyAccountsTable = pgTable(
  "mobile_money_accounts",
  {
    id: serial("id").primaryKey(),
    firmId: integer("firm_id")
      .notNull()
      .references(() => firmsTable.id, { onDelete: "cascade" }),
    clientId: integer("client_id")
      .notNull()
      .references(() => clientsTable.id, { onDelete: "cascade" }),
    provider: text("provider").notNull().$type<MobileMoneyProvider>(),
    // Merchant/subscriber number (phone number or merchant code) for this
    // Mobile Money account -- purely informational, does not change which
    // SYSCOHADA account (552xxx) the provider posts to.
    accountNumber: text("account_number").notNull(),
    label: text("label"),
    isActive: text("is_active").notNull().default("true"),
    // Cached running balance (FCFA), kept in sync by every posted
    // inflow/outflow/transfer -- lets the Trésorerie dashboard show a live
    // balance without re-aggregating every transaction on each read.
    balance: integer("balance").notNull().default(0),
    createdById: integer("created_by_id").references(() => usersTable.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),
  },
  (table) => [
    index("mobile_money_accounts_client_id_idx").on(table.clientId),
    unique("mobile_money_accounts_client_provider_number_unique").on(
      table.clientId,
      table.provider,
      table.accountNumber,
    ),
  ],
);

export const insertMobileMoneyAccountSchema = createInsertSchema(mobileMoneyAccountsTable).omit({
  id: true,
  balance: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertMobileMoneyAccount = z.infer<typeof insertMobileMoneyAccountSchema>;
export type MobileMoneyAccountRow = typeof mobileMoneyAccountsTable.$inferSelect;

// "inflow": money entering the account (invoice settlement, manual daily
// sale). "outflow": step 1 of a bank repatriation (leaves the Mobile Money
// account, lands in the 585 transit account). "transfer_received": step 2
// of a bank repatriation (585 transit clears into 5211 Banque).
export const MOBILE_MONEY_TX_TYPES = ["inflow", "outflow", "transfer_received"] as const;
export type MobileMoneyTxType = (typeof MOBILE_MONEY_TX_TYPES)[number];

export const MOBILE_MONEY_TX_STATUSES = ["initiated", "completed"] as const;
export type MobileMoneyTxStatus = (typeof MOBILE_MONEY_TX_STATUSES)[number];

export const mobileMoneyTransactionsTable = pgTable(
  "mobile_money_transactions",
  {
    id: serial("id").primaryKey(),
    firmId: integer("firm_id")
      .notNull()
      .references(() => firmsTable.id, { onDelete: "cascade" }),
    clientId: integer("client_id")
      .notNull()
      .references(() => clientsTable.id, { onDelete: "cascade" }),
    mobileMoneyAccountId: integer("mobile_money_account_id")
      .notNull()
      .references(() => mobileMoneyAccountsTable.id, { onDelete: "cascade" }),
    // Traceability: set for inflows generated by an invoice settlement
    // (module Facturier). Null for manual daily sales and repatriations.
    invoiceId: integer("invoice_id").references(() => invoicesTable.id, {
      onDelete: "set null",
    }),
    // The general-ledger transaction carrying the actual SYSCOHADA journal
    // lines for this movement (step 1 for a transfer).
    transactionId: integer("transaction_id").references(() => transactionsTable.id, {
      onDelete: "set null",
    }),
    // For a "transfer_received" (step 2 receipt confirmation), points back
    // to the "outflow" row it completes.
    parentMobileMoneyTransactionId: integer("parent_mobile_money_transaction_id"),
    type: text("type").notNull().$type<MobileMoneyTxType>(),
    status: text("status").notNull().$type<MobileMoneyTxStatus>().default("completed"),
    amount: integer("amount").notNull(),
    feeAmount: integer("fee_amount").notNull().default(0),
    referenceCode: text("reference_code"),
    label: text("label").notNull(),
    date: timestamp("date", { withTimezone: true }).notNull(),
    createdById: integer("created_by_id").references(() => usersTable.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("mobile_money_transactions_account_id_idx").on(table.mobileMoneyAccountId),
    index("mobile_money_transactions_client_id_idx").on(table.clientId),
    index("mobile_money_transactions_invoice_id_idx").on(table.invoiceId),
  ],
);

export const insertMobileMoneyTransactionSchema = createInsertSchema(
  mobileMoneyTransactionsTable,
).omit({
  id: true,
  createdAt: true,
});
export type InsertMobileMoneyTransaction = z.infer<typeof insertMobileMoneyTransactionSchema>;
export type MobileMoneyTransactionRow = typeof mobileMoneyTransactionsTable.$inferSelect;
